baseURL = 'http://tristinforbus.com/'
languageCode = 'en-us'
title = 'tristin forbus'
theme = 'whiteplain'

[taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"

[[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Archives"
    identifier = "archives"
    url = "/archives/"
    weight = 2

[markup]
    [markup.highlight]
        anchorLineNos = false
        codeFences = false
        guessSyntax = false
        hl_inline = false
        lineAnchors = ''
        lineNoStart = 1
        lineNumbersInTable = true
        noClasses = false
        noHl = false
        style = 'github'
        tabWidth = 4
